name: detekt

on:
  pull_request:
    paths-ignore:
      - 'app-ios/**'

jobs:
  detekt:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-java

      - name: Run detekt
        id: detekt
        run: ./gradlew detekt --stacktrace

      - name: Save PR event
        if: failure()
        run: |
          mkdir -p ./pr
          echo '${{ toJson(github.event) }}' > ./pr/event.json

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pr
          path: pr/
