name: 'PR Labeler'

on:
  pull_request:

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add label
        uses: actions/labeler@v5
        with:
          configuration-path: .github/configs/labeler.yml

  call_workflow:
    needs: [label]
    runs-on: ubuntu-latest
    steps:
      - id: labels
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          json=$(gh pr view "$PR_NUMBER" --json labels | jq -c '.labels|map(.name)')
          echo "json=$json" >> "$GITHUB_OUTPUT"
      - name: Echo Label
        run: echo "${{steps.labels.outputs.json}}"
      - if: contains(fromJSON(steps.labels.outputs.json), 'type:iOS 🍎')
        uses: ./.github/workflows/swiftlint.yml
